server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

metrics_generator:
  storage:
    path: /tmp/tempo-metrics
  processor:
    service_graphs: {}
    span_metrics: {}

storage:
  trace:
    backend: local                     # Store traces locally for development
    local:
      path: /tmp/tempo/traces
    wal:
      path: /tmp/tempo/wal             # Write-Ahead Log
